services:
  - type: web
    name: redgps-examen
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DATA_DIR
        value: /var/data
    disk:
      name: redgps-examen-data
      mountPath: /var/data
      sizeGB: 1
